apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rnqskxqjk-python 
  janus-idp.io/tekton: rnqskxqjk-python
  backstage.io/kubernetes-id: rnqskxqjk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rnqskxqjk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  