apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rnqskxqjk-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:cfcb8f02052a3862828df4feb28a7b3e1e5842a6@sha256:2eb2cbf9dfff23c57dc06d17f27efa37e1be27fe703bc2ee94803ab00f2af410
          name: container-image
